version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/bookdb
